/**
 * Wire types mirroring `agent-bus-core::models` and `agent-bus-core::channels`
 * (see the parent repo's Rust source). Field names, JSON casing and
 * presence/omission rules are copied exactly from the `serde` derives so the
 * Worker is byte-for-byte compatible with the on-site hub. Additive fields
 * introduced by agent-hub#79 are marked below and are always optional.
 *
 * Rust `#[serde(skip_serializing_if = "Option::is_none")]` fields are modeled
 * as TypeScript optional properties (`field?: T`) and must be genuinely
 * omitted (not set to `undefined` explicitly is fine — `JSON.stringify` drops
 * `undefined` values — but never set them to `null`).
 *
 * Rust `Option<T>` fields WITHOUT a skip attribute (e.g. `ArbitrationState`)
 * are modeled as `field: T | null` and must always be present, `null` when
 * absent.
 */

export const PROTOCOL_VERSION = "1.0";

/**
 * JSON-safe value. Used (instead of `unknown`) for every field that crosses
 * a Durable Object RPC boundary (`stub.method(...)` calls in `index.ts`),
 * because Workers RPC's `Rpc.Serializable<T>` check requires `T extends
 * Serializable<T>` — which is trivially false for `T = unknown` (nothing
 * `extends unknown` except `unknown`/`any` itself), collapsing the whole
 * method's stub type to `never`. `serde_json::Value` on the Rust side has no
 * such restriction, but every value it actually carries in this codebase is
 * plain JSON, so this is a faithful, RPC-safe substitute.
 *
 * Depth is capped at 5 levels rather than defined as a naturally infinite
 * recursive type: an unbounded self-referential type here, combined with the
 * RPC layer's own recursive `Serializable<T>`/`Stubify<T>` mapped types,
 * makes the TypeScript compiler give up with "Type instantiation is
 * excessively deep and possibly infinite" (TS2589). Five levels covers every
 * metadata shape this codebase actually sends (host/repo/session tags,
 * nested claim/reroute objects); genuinely deeper payloads would need a
 * pre-serialized JSON string instead, the way `metadata` is stored in the
 * DO's own SQLite columns.
 */
export type JsonPrimitive = string | number | boolean | null;
type JsonValue0 = JsonPrimitive;
type JsonValue1 = JsonPrimitive | JsonValue0[] | { [key: string]: JsonValue0 };
type JsonValue2 = JsonPrimitive | JsonValue1[] | { [key: string]: JsonValue1 };
type JsonValue3 = JsonPrimitive | JsonValue2[] | { [key: string]: JsonValue2 };
type JsonValue4 = JsonPrimitive | JsonValue3[] | { [key: string]: JsonValue3 };
export type JsonValue = JsonPrimitive | JsonValue4[] | { [key: string]: JsonValue4 };

export type Priority = "low" | "normal" | "high" | "urgent";
export const VALID_PRIORITIES: Priority[] = ["low", "normal", "high", "urgent"];

/** agent-hub#79: message replication sensitivity. Default `"internal"`. */
export type Sensitivity = "internal" | "no-offsite";

/** agent-hub#79: client-side sync bookkeeping (not stored server-side). */
export type SyncState = "local" | "pending_sync" | "synced";

/** agent-hub#79: presence roaming context. */
export type NetworkContext = "lab-p2p" | "lab-lan" | "offsite" | "offline";

/** Mirrors `agent_bus_core::models::Message`. */
export interface Message {
  id: string;
  timestamp_utc: string;
  protocol_version: string;
  from: string;
  to: string;
  topic: string;
  body: string;
  thread_id?: string;
  /** `#[serde(default)]` SmallVec — always present, `[]` when empty. */
  tags: string[];
  priority: string;
  /** `#[serde(default)]` — always present. */
  request_ack: boolean;
  reply_to?: string;
  /** `#[serde(default)]` — always present; `null` when the sender omitted it. */
  metadata: JsonValue;
  stream_id?: string;

  // --- agent-hub#79 additive fields (all optional, backward compatible) ---
  /** UUIDv7 generated by the sender; the idempotency key for outbox replay / sync dedupe. */
  client_msg_id?: string;
  /** Hostname that produced the message. */
  origin_host?: string;
  /** Hub (asuspro13 / agentbus.dtmventures.com / ...) that first accepted the message. */
  origin_hub?: string;
  /** Per-origin monotonic sequence number, paired with `hlc` for stable cross-hub ordering. */
  origin_seq?: number;
  /** Hybrid logical clock string, e.g. `"<millis>-<counter>-<origin_hub>"`. */
  hlc?: string;
  /** Client-side only; the cloud tier does not set or rely on this. */
  sync_state?: SyncState;
  /** `"no-offsite"` messages are rejected by the cloud tier (see SYNC-CONTRACT.md). */
  sensitivity?: Sensitivity;
}

/** Mirrors `agent_bus_core::models::Presence`. */
export interface Presence {
  agent: string;
  status: string;
  protocol_version: string;
  timestamp_utc: string;
  session_id: string;
  /** `#[serde(default)]` — always present. */
  capabilities: string[];
  /** `#[serde(default)]` — always present. */
  metadata: JsonValue;
  ttl_seconds: number;

  // --- agent-hub#79 additive field ---
  network_context?: NetworkContext;
  // --- agent-hub#82 additive field: set only for presence relayed via
  // `POST /sync/push-presence`, mirroring `Message.origin_hub`. Absent for
  // presence set directly via `PUT /presence/:agent`. ---
  origin_hub?: string;
}

/** Mirrors `agent_bus_core::redis_bus::Notification`. */
export interface Notification {
  id: string;
  agent: string;
  created_at: string;
  reason: string;
  requires_ack: boolean;
  message: Message;
  notification_stream_id?: string;
}

/** Mirrors `agent_bus_core::redis_bus::PendingAck`. */
export interface PendingAck {
  message_id: string;
  recipient: string;
  sent_at: string;
  stale: boolean;
}

export type ClaimStatus = "pending" | "granted" | "contested" | "review_assigned";
export type ResourceLeaseMode = "shared" | "shared_namespaced" | "exclusive";
export type ResourceScope = "repo" | "machine";

/** Mirrors `agent_bus_core::channels::RerouteSuggestion`. */
export interface RerouteSuggestion {
  original_resource: string;
  suggested_resource: string;
  isolation_hint: string;
  reason: string;
}

/** Mirrors `agent_bus_core::channels::OwnershipClaim`. */
export interface OwnershipClaim {
  resource: string;
  agent: string;
  priority_argument: string;
  timestamp: string;
  status: ClaimStatus;
  mode: ResourceLeaseMode;
  namespace?: string;
  scope_kind?: string;
  scope_path?: string;
  /** `#[serde(default, skip_serializing_if = "Vec::is_empty")]` — omitted when empty. */
  repo_scopes?: string[];
  thread_id?: string;
  lease_ttl_seconds: number;
  expires_at?: string;
  scope: ResourceScope;
  reroute_suggestion?: RerouteSuggestion;
}

/** Mirrors `agent_bus_core::channels::ArbitrationState`. Both Options lack
 * `skip_serializing_if` in Rust, so they are always present (`null` when absent). */
export interface ArbitrationState {
  resource: string;
  claims: OwnershipClaim[];
  winner: string | null;
  resolution_reason: string | null;
}

/** A resource lifecycle event (mirrors `agent_bus_core::models::ResourceEvent`). */
export interface ResourceEvent {
  event: string;
  agent: string;
  resource: string;
  timestamp: string;
  stream_id?: string;
}

/** Health response. Only the fields the cloud tier can meaningfully answer
 * are populated; fleet-identifying counts are never exposed on the open
 * `/health` route (mirrors the Rust hub's own redaction posture — see
 * `http_health_handler`'s comment on topology leaks over a routable bind). */
export interface Health {
  ok: boolean;
  protocol_version: string;
  build_version: string;
  redis_url: string;
  database_url: string | null;
  database_ok: boolean | null;
  database_error: string | null;
  storage_ready: boolean;
  runtime: string;
  codec: string;
  hub_identity?: string;
}

export interface ApiError {
  error: string;
  message?: string;
}
